from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import uvicorn


ROOT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = ROOT_DIR / "backend"
MODEL_ASSETS_DIR = ROOT_DIR / "runtime_data" / "model_assets"
CRITICAL_FILES = [BACKEND_DIR / "api.py", MODEL_ASSETS_DIR / "features_meta.json"]
VALIDATION_SCRIPT = BACKEND_DIR / "validate_pipeline.py"
VALIDATION_REPORT = ROOT_DIR / "runtime_data" / "validation_report.txt"
READY_STATUS = "Overall pipeline status: READY FOR USE"


def print_header() -> None:
    line = "=" * 60
    print(line)
    print("Starting 4G RAN AI Backend...")
    print(line)


def check_critical_files() -> bool:
    missing = [path for path in CRITICAL_FILES if not path.exists()]
    if not missing:
        return True

    print("ERROR: Missing required startup files:")
    for path in missing:
        print(f" - {path.name}")
    print("Please restore missing files and retry.")
    return False


def run_validation() -> bool:
    if not VALIDATION_SCRIPT.exists():
        print("ERROR: --validate requested but backend/validate_pipeline.py is missing.")
        return False

    print("Running pipeline validation before server startup...")
    result = subprocess.run(
        [sys.executable, str(VALIDATION_SCRIPT)],
        cwd=str(ROOT_DIR),
        check=False,
    )
    if result.returncode != 0:
        print(f"ERROR: Validation script failed with exit code {result.returncode}.")
        return False

    if not VALIDATION_REPORT.exists():
        print("ERROR: runtime_data/validation_report.txt was not generated by backend/validate_pipeline.py.")
        return False

    report_text = VALIDATION_REPORT.read_text(encoding="utf-8", errors="replace")
    if READY_STATUS not in report_text:
        print("ERROR: Validation did not pass. See validation_report.txt for details.")
        return False

    print("Validation passed. Starting API server...")
    return True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Start the 4G RAN FastAPI backend.")
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Run backend/validate_pipeline.py first and start the server only on READY FOR USE.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    print_header()

    if not check_critical_files():
        return 1

    if args.validate and not run_validation():
        return 1

    print("Launching FastAPI on http://0.0.0.0:8000 (reload=False)")
    # In production, auto-reload must remain disabled for stability and predictable process behavior.
    uvicorn.run("backend.api:app", host="0.0.0.0", port=8000, reload=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
